ADD: get_airnow functionality
ARM-DOE/ACT pull request #380
Opened 2022-01-07 18:09 UTC by jhemedin

Added function to pull the AirNow data from the AirNow API. Two of the functions just pull the data and display them on screen and the last one will download a file. Working on adding the option to download files with the other functions that just print to the screen.

Need to figure out how to unit test since a users private token is needed to access the data.

2022-02-23 14:22 UTC, AdamTheisen commented
@mgrover1 would you want to tab a stab at helping on this PR?  This is a new capability to work with the EPA's airnow portal to pull data. https://docs.airnowapi.org/.  The main thing we need is to set up unit tests for this but the portal requires a username/token so we were going to follow like the testing of the ARM download data test and have environment variables set on TRAVIS-CI with a username/token.  I'm fine setting up an account and using my credentials there but also open if you have other ideas.

2022-02-23 14:43 UTC, mgrover1 commented
@AdamTheisen Sure! I can take a look at this!

2022-06-10 19:08 UTC, AdamTheisen commented
I've made a fair amount of updates here.  

1. I've simplified get_AirNow_forecast and get_AirNow_obs to remove the format as we are returning an xarray dataset anyways
2. Revamped get_AriNow to return an xarray object instead of downloading files to be consistent with the others.  I also simplified and renamed to get_AirNow_bounded_obs
3. Added tests to test_discovery and in doing so found a failing test from cropscape that I fixed.

2022-06-10 19:46 UTC, zssherman commented
Looks good, only thing failing at the moment is coveralls, but with new code, i kinda expect it. There are unittests you added so once the rest passes, think this would be good to merge.

2022-06-10 19:46 UTC, zssherman approved these changes

2022-06-10 20:21 UTC, AdamTheisen commented
Given that these tests will use secrets, it won't run during the PR testing.  I've updated the coverage failure to 1.5% to account for this.

2022-06-10 20:31 UTC, mgrover1 requested changes
Just a few suggestions @AdamTheisen

2022-06-10 20:31 UTC, mgrover1 commented on act/discovery/get_airnow.py
> +        The access token for accesing the AirNowAPI web server
One small suggestion - can you add the link here to the AirNowAPI? Just thinking about the user trying to find where to get their login.

2022-06-10 20:31 UTC, mgrover1 commented on act/discovery/get_airnow.py
> +def get_AirNow_forecast(token, date, zipcode=None, latlon=None, distance=25):
Can you make this function all lower-case?

2022-06-10 20:31 UTC, mgrover1 commented on act/discovery/get_airnow.py
> +def get_AirNow_obs(token, date=None, zipcode=None, latlon=None, distance=25):
Same here - can you make this all lowercase?

2022-06-10 20:31 UTC, mgrover1 commented on act/discovery/get_airnow.py
> +        The access token for accesing the AirNowAPI web server
And add the link here too.

2022-06-10 20:31 UTC, mgrover1 commented on act/discovery/get_airnow.py
> +def get_AirNow_bounded_obs(token, start_date, end_date, latlon_bnds, parameters='OZONE,PM25', data_type='B',
Lowercase here

2022-06-10 20:31 UTC, mgrover1 commented on act/discovery/get_airnow.py
> +    token : str
And link in the in the docstring

2022-06-10 20:45 UTC, AdamTheisen commented
@mgrover1 these latest updates should take care of your changes that were requested.  Added in a link to each function description and updated the functions to be lower case

2022-06-10 20:49 UTC, mgrover1 approved these changes
Great! Thanks for making those changes!

2022-06-10 20:56 UTC, mgrover1 commented
Once the tests pass, we can merge away 👍

2022-06-10 21:38 UTC, merged