ENH: Updating example to show how to clean object and plot QC
ARM-DOE/ACT pull request #455
Opened 2022-04-28 19:19 UTC by AdamTheisen

2022-04-28 21:13 UTC, zssherman approved these changes

2022-04-29 17:39 UTC, mgrover1 requested changes
One small change in spelling

2022-04-29 17:39 UTC, mgrover1 commented on examples/plot_qc.py
> +plotting the data and it's QC flags
it's --> its

2022-05-02 13:51 UTC, mgrover1 approved these changes
Looks great @AdamTheisen !

2022-05-02 14:43 UTC, merged