Adding TAR and gunzip support
ARM-DOE/ACT pull request #549
Opened 2022-11-02 20:48 UTC by kenkehoe

This adds in some functions to create and extract from TAR/gunzip files. Also updated the netCDF reader to just work with TAR and gunzip files. Resolves #541 .

2022-11-03 15:09 UTC, kenkehoe commented
I am getting a strange error?

FAILED act/tests/test_io.py::test_read_netcdf_tarfiles - NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpe7rvjwup\\uwSmSKsq7lOAEjrf5W6z\\sgpmetE13.b1.20190101.000000.cdf'

Any idea what the issue could be? I am creating a random directory name as part of the process.

2022-11-03 15:27 UTC, AdamTheisen commented
@kenkehoe I'm rerunning the tests to make sure but I'm wondering if it has to do with creating a directory outside the package on this runner.  I wonder if creating a temp directory somewhere in the ACT folder structure would have different permissions.

2022-11-04 13:40 UTC, AdamTheisen commented
@kenkehoe  I just resolved a conflict with the files so it's running again but I can try and test out on my windows machine later today on the pytest error.

```
FAILED act/tests/test_io.py::test_read_netcdf_tarfiles - PermissionError: [WinError 32] The process cannot access the file 
because it is being used by another process: 
'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpwod4mqnu\\aovgrX0cOy2UjSFAj0vz\\sgpmetE13.b1.20190101.000000.cdf'

FAILED act/tests/test_io.py::test_read_netcdf_gztarfiles - ValueError: did not find a match in any of xarray's currently 
installed IO backends ['netcdf4', 'scipy']. Consider explicitly selecting one of the installed engines via the ``engine`` 
parameter, or installing additional IO dependencies, see:
```

2022-11-07 13:55 UTC, AdamTheisen commented
@kenkehoe  I was able to recreate the error on my windows machine and will try and work through it this week as I can.

2022-11-07 17:50 UTC, kenkehoe commented
@AdamTheisen let me know how I can help with this. I did a few changes/comment out code to try and help determine where the issue could be.

2022-11-07 21:44 UTC, AdamTheisen commented
@kenkehoe I don't have it fully figured out yet but I think it has to do with the circular nature of how you have it set up.  I.e. that in `read_netcdf` you call `check_if_tar_gz_file` where it checks the file and then calls `read_netcdf` once it's unpacked the files.  I think this is complicating things and causing issues with file permissions on windows.  It might be best to have the function unpack the files and return a list of filenames for `read_netcdf` to then proceed with reading.

The other issue was that the files returned from line 178 in `test_read_netcdf_gztarfiles` were tar files which I guess would be untarred if passed back through `read_netcdf` but again, I think it's too many circular loops here.

Thoughts?

2022-11-07 21:46 UTC, kenkehoe commented
Yeah, I was thinking that may be the issue. I'll refactor it and see I can make it less circular.

2022-11-13 21:08 UTC, AdamTheisen commented
@kenkehoe  it looks like a couple pep8 issues

```
.\act\tests\test_io.py:789:5: E303 too many blank lines (2)
.\act\tests\test_io.py:796:1: W391 blank line at end of file
```

2022-11-14 15:39 UTC, kenkehoe commented
@AdamTheisen I don't understand the errors. Can you just rerun?

2022-11-14 16:52 UTC, kenkehoe commented
All checks have passed. I just shed a tear!

2022-11-14 17:04 UTC, AdamTheisen commented
@kenkehoe my only thought here is if the io_utils.py file should be in the utils directory

2022-11-14 18:00 UTC, AdamTheisen commented
@zssherman  or @mgrover1  any thoughts here on the utils file?

2022-11-14 18:46 UTC, zssherman commented
I think either or is fine, or the argument can be made for both, it is unpacking and changing files etc. But I would say it's not necessarily reading a file in the aspect of some of the other readers. My vote would be utils

2022-11-14 20:16 UTC, mgrover1 commented
@AdamTheisen - I think it would be best to move to the `utils` module, to be consistent with the rest of the utils functions. 

@kenkehoe can you move `io_utils.py` over there?

2022-11-14 22:01 UTC, kenkehoe commented
OK I'll move the functions to the utils area.

2022-11-14 22:56 UTC, zssherman commented
@kenkehoe PEP8 line continuation, and @mgrover1 the readded mmcr code PR will just squash when this is merged correct? Besides that, once test pass, i think this is good to go

2022-11-14 23:19 UTC, kenkehoe commented
@zssherman I resolved the merge conflict from MMCR PR in my code. So once the tests pass should be good to go.

2022-11-14 23:41 UTC, zssherman approved these changes

2022-11-14 23:46 UTC, zssherman commented
Looks good to me, @AdamTheisen @mgrover1 any last thoughts? Figured a large PR good for one last check

2022-11-15 14:38 UTC, AdamTheisen requested changes
@kenkehoe @zssherman other than this one change I think it should be good to go.

2022-11-15 14:38 UTC, AdamTheisen commented on act/io/__init__.py
> +        'io_utils': ['pack_tar',
@kenkehoe I think we need to move this over to the __init__ in the utils area as well.

2022-11-15 18:37 UTC, merged