MNT: Change naming to MET as its plotting met data.
ARM-DOE/ACT pull request #653
Opened 2023-04-04 16:11 UTC by zssherman

- [ ] Closes #652 
- [ ] Documentation reflects changes
- [ ] PEP8 Standards or use of linter

2023-04-04 16:15 UTC, mgrover1 commented on examples/plotting/plot_met.py
> +This is a simple example for how to plot a timeseries of MET
```suggestion
This is a simple example for how to plot a timeseries of surface meteorology (MET) data
```

2023-04-04 16:15 UTC, mgrover1 requested changes
One small suggestion

2023-04-04 16:17 UTC, zssherman commented
Ooo yeah good point! Will fix that now

2023-04-04 16:46 UTC, zssherman commented
@rcjackson Did pysp2 update anything that would change the waveform stats calculation?

2023-04-04 16:50 UTC, zssherman commented
Seeing some unit changes etc recently to it.

2023-04-04 16:53 UTC, AdamTheisen commented
@zssherman if we are changing this to just be a simple plot of the time series data, we can remove the LCL calculations from this example.  I was somewhat thinking of this the other way around in that we should update the example to plot the SONDE time series with the LCL plotted in a plot of the altitude or something like that.  I think that is what @rcjackson was maybe intending to do with this one.  Thoughts?

2023-04-04 18:36 UTC, zssherman commented
@AdamTheisen Ah makes sense! I can switch things around to be what was originally intended!

2023-04-04 19:07 UTC, zssherman commented
@AdamTheisen Example has been updated for sonde data. Updating the unit tests now to match the pysp2 changes that are failing the CI.

2023-04-04 19:18 UTC, zssherman commented
@mgrover1 Done

2023-04-04 19:32 UTC, zssherman commented
Confused on this class init failures for only python 3.8:
TypeError: __init__() got an unexpected keyword argument 'base'

2023-04-04 19:43 UTC, zssherman commented
Ah so all tests failing for that base error are all older xarray version its looks like using base parameter in resample.

2023-04-04 19:44 UTC, zssherman commented
@AdamTheisen @mgrover1 Do we drop 3.8 as we are three ahead with 3.9, 3.10 and 3.11 or do we find a work around for this base error in resampling.

2023-04-04 19:49 UTC, mgrover1 commented
Let's pin pandas<2.0... it is an issue on the xarray/pandas/flox side. We should consider pinning version in tests/such

2023-04-04 19:50 UTC, zssherman commented
@mgrover1 Sounds like a plan!

2023-04-04 19:55 UTC, zssherman commented
@mgrover1 I can't remember if that syntax is right for requirements.txt. I know it is for the .yml. Also two numpy installs removed one of them.

2023-04-04 19:57 UTC, zssherman commented
And do you have the issue or where you found the info on the pandas/flox issue.

2023-04-04 19:58 UTC, mgrover1 commented
https://github.com/pydata/xarray/issues/7716

2023-04-04 20:16 UTC, zssherman commented
@mgrover1 Cool seems to be working! Just the usual stalled tests.

2023-04-04 21:11 UTC, zssherman commented
@AdamTheisen @mgrover1 Once you both think this is good to merge, I can go do that

2023-04-05 12:31 UTC, mgrover1 approved these changes

2023-04-05 17:15 UTC, AdamTheisen approved these changes

2023-04-05 17:27 UTC, merged