Base functionality to create movies from images
ARM-DOE/ACT pull request #776
Opened 2023-12-18 22:36 UTC by AdamTheisen

- [ ] Closes #469 
- [ ] Tests added
- [ ] Documentation reflects changes
- [ ] PEP8 Standards or use of linter
- [ ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

2023-12-18 22:42 UTC, zssherman requested changes

2023-12-18 22:42 UTC, zssherman commented on act/tests/utils/test_io_utils.py
> +def test_generate_movie():
I would make the test optional as well

2023-12-18 22:42 UTC, zssherman commented on act/utils/io_utils.py
> +            'Cartopy needs to be installed on your ' 'system to make geographic display plots.'
Cartopy to Moviepy

2023-12-19 15:48 UTC, AdamTheisen commented
I had a feeling that the test was not going to work on Windows... I'll try and test that out some more when I get a chance.

2023-12-19 17:56 UTC, AdamTheisen commented
@zssherman this should be good to go. 

@kenkehoe we can test this out as an optional dependency for now and can always adjust in the future.  You can pass it a list of images or a list of URLs and is pretty straight forward at the moment.

2023-12-19 18:30 UTC, zssherman approved these changes

2023-12-19 18:52 UTC, merged