Adding in new function
ARM-DOE/ACT pull request #845
Opened 2024-07-17 16:58 UTC by ajsockol

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Documentation reflects changes
- [ ] PEP8 Standards or use of linter
- [ ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

2024-07-17 17:35 UTC, zssherman requested changes

2024-07-17 17:35 UTC, zssherman commented on act/utils/data_utils.py
> +def convert_2d_to_1d(ds_object, parse=None, variables=None, keep_name_if_one=False,
@ajsockol Can we rename ds_object to ds in this new code to be consistent with other functions in ACT.

2024-07-17 17:35 UTC, zssherman commented on act/utils/data_utils.py
> +    ...
Can we remove the whitespace and 3 . line and leave one space between intro sentence and Parameter header

2024-07-17 17:35 UTC, zssherman commented on act/utils/data_utils.py
> +
Removal of one space

2024-07-17 17:35 UTC, zssherman commented on act/utils/data_utils.py
> +
Remove 1 space as well her
e

2024-07-17 17:35 UTC, zssherman commented on act/utils/data_utils.py
> +    new_ds_object = ds_object.copy()
Can we call new_ds_object, new_ds

2024-07-17 17:36 UTC, zssherman commented
@ajsockol Thanks for the PR! I added some review comments. Also could we add unit tests to this PR as well for the new code?

2024-07-17 18:17 UTC, ajsockol commented
I added all the changes you mentioned except the testing. I'll add that next!

2024-07-17 19:02 UTC, ajsockol commented
Okay, I've added the tests. Now to just figure out why the linting keeps failing

2024-07-17 19:19 UTC, zssherman commented
@ajsockol Can you try installing pre-commit? I should help with the linting issues

2024-07-17 19:28 UTC, mgrover1 commented
> @ajsockol Can you try installing pre-commit? It should help with the linting issues. I'm also trying to find out why the test_arm_qc tests are failing

It should be in your `act_env` development environment

within your main ACT directory you can run

```bash
pre-commit install .
```

Then, when you commit, it will auto-lint and fix where needed.

2024-07-17 19:39 UTC, zssherman commented
@kenkehoe I'm still trying to familiarize with QC code of ACT, but do you possibly know why this PR might be failing the ARM QC tests?

2024-07-17 19:42 UTC, ajsockol commented
@mgrover1 when i try to run `pre-commit install .` in my ACT directory (when I'm in my act_env development environment), I get this error:

![Screenshot 2024-07-17 at 2 42 43 PM](https://github.com/user-attachments/assets/81e53ccb-ac8b-4ed3-9087-ef78963915e5)

2024-07-17 20:26 UTC, zssherman commented
@ajsockol Maybe try pre-commit install from within the act direcctory no .

2024-07-17 21:36 UTC, kenkehoe commented
@zssherman  I know why the QC test is failing. We use a production DQR to test the functionality of the ARM DQR web-service. The DQR used was reprocessed so it is now not returned in the API call. I have a fix for this in my current PR. It's a simple fix if we want to include it in this PR to allow it to pass the tests.

In act.tests.qc.test_arm_qc.py change line 15 to:

ds = add_dqr_to_qc(ds, assessment='Reprocessed,Suspect,Incorrect')

2024-07-17 21:43 UTC, zssherman commented
@kenkehoe Ah makes sense! Thanks for the info! We could always wait to have your PR merge in and then can rerun the tests here.

2024-07-18 18:47 UTC, ajsockol commented
Okay I got things figured out and was able to push changes through SSH. It looks like what's failing now are the arm_qc tests

2024-07-18 18:49 UTC, zssherman commented
@ajsockol Cool, yeah looks like the linter etc are passing. Ken's PR fixes that QC issue so we can wait for that one to get approved then once its merge rerun the tests here.

2024-07-25 15:38 UTC, ajsockol commented
Okay, I copied and pasted a fix from Ken for one of the tests that was failing, but there is still one test failing from tests/discovery/test_asos.py::test_get_region that seems to be something out of my hands. @zssherman do you know what might be going wrong there?

2024-07-25 15:51 UTC, zssherman commented
@ajsockol It is a connection error, i'll rerun the tests which will fix it.

2024-07-25 18:04 UTC, AdamTheisen approved these changes

2024-07-25 18:09 UTC, zssherman approved these changes

2024-07-25 19:55 UTC, merged