Updates to making QC Summary files
ARM-DOE/ACT pull request #852
Opened 2024-08-28 22:17 UTC by kenkehoe

These are some incremental updates to the method that creates a QC Summary. Also, working on improving the output netCDF file by improving how we correct the Dataset when writing to follow CF. Added some pytest.warn() to capture warnings and ensure they occur in our testing.

- [X ] Tests added
- [ X] Documentation reflects changes
- [ X] PEP8 Standards or use of linter
- [X ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

2024-08-28 23:23 UTC, zssherman commented
@kenkehoe Thanks for the PR, I'll give this a review tomorrow

2024-08-29 22:02 UTC, zssherman requested changes
Made some minor code requested changes, but besides that looks good to me

2024-08-29 22:02 UTC, zssherman commented on act/qc/qc_summary.py
> +                #     warnings.warn(f'Unable to process scalar variable {var_name}. '
Can we remove this commented out code as well?

2024-08-30 15:39 UTC, zssherman requested changes

2024-08-30 15:39 UTC, zssherman commented on act/qc/arm.py
> +        If a quality control varible for the data varialbe does not exist,
```suggestion
        If a quality control variable for the data variable does not exist,
```

2024-08-30 15:39 UTC, zssherman commented on act/qc/arm.py
> +    # convert CF variables, convert the time varible for this routine only.
```suggestion
    # convert CF variables, convert the time variable for this routine only.
```

2024-08-30 15:39 UTC, zssherman commented on act/qc/arm.py
> +            # Do not process time varibles
```suggestion
            # Do not process time variables
```

2024-08-30 15:39 UTC, zssherman commented on act/qc/clean.py
> +        # qc_lookup={'Incorrect': 'Bad', 'Suspect': 'Indeterminate'},
```suggestion
```

2024-08-30 15:39 UTC, zssherman commented on act/qc/qc_summary.py
> +                # if return_ds[var_name].ndim == 0:
```suggestion
```

2024-08-30 15:39 UTC, zssherman commented on act/qc/qc_summary.py
> +                #     warnings.warn(f'Unable to process scalar variable {var_name}. '
```suggestion
```

2024-08-30 15:39 UTC, zssherman commented on act/qc/qc_summary.py
> +                #                   'Scalar variables currently not implemented.')
```suggestion
```

2024-08-30 15:39 UTC, zssherman commented on act/qc/qc_summary.py
> +                #     continue
```suggestion
```

2024-08-30 21:50 UTC, zssherman commented
@kenkehoe I made some changes etc, are you good with me merging this in?

2024-09-03 19:12 UTC, kenkehoe commented
Yes, you can merge your changes.

2024-09-04 15:56 UTC, AdamTheisen approved these changes

2024-09-04 15:57 UTC, AdamTheisen commented
@zssherman this looks good to me.  If all changes you requested have been implemented, I would say merge away!

2024-09-04 15:57 UTC, merged

2024-09-04 15:57 UTC, mgrover1 approved these changes